const todos = [
    {
        id: 1,
        title: "test 1",
        assignee: "assignee 1",
        assigned: "assigned 1",
        category: "category 1",
        description: "description 1",
        status: "in progress",
        dateAdded: "00-00-00",
        dateCompleted: "00-00-00",
    },
    {
        id: 2,
        title: "test 2",
        assignee: "assignee 2",
        assigned: "assigned 2",
        category: "category 2",
        description: "description 2",
        status: "in progress",
        dateAdded: "00-00-00",
        dateCompleted: "00-00-00",
    },
    {
        id: 3,
        title: "test 3",
        assignee: "assignee 3",
        assigned: "assigned 3",
        category: "category 3",
        description: "description 3",
        status: "in progress",
        dateAdded: "00-00-00",
        dateCompleted: "00-00-00",
    },
    {
        id: 4,
        title: "test 4",
        assignee: "assignee 4",
        assigned: "assigned 4",
        category: "category 4",
        description: "description 4",
        status: "in progress",
        dateAdded: "00-00-00",
        dateCompleted: "00-00-00",
    },
];

module.exports = todos;
